# Generated by Django 5.2.1 on 2025-05-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('IN', 'Sign In'), ('OUT', 'Sign Out')], default='IN', max_length=3),
        ),
    ]
