# Generated by Django 5.2.1 on 2025-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/images/'),
        ),
    ]
