# Generated by Django 5.2.1 on 2025-06-04 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-sign_in', '-sign_out']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sign_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sign_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='emergency_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='emergency_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='child',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='child_pix/'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('age_range', models.CharField(help_text="e.g., '2-3 years', '3-5 years'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='attendance.center')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('center', 'name')},
            },
        ),
        migrations.AddField(
            model_name='child',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='attendance.room'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='attendance.room'),
        ),
    ]
