# Generated by Django 5.2.1 on 2025-06-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
    ]
