# Generated by Django 5.2.1 on 2025-05-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
    ]
