# Generated by Django 5.2.1 on 2025-06-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='emergency_contact',
            field=models.CharField(default='Emergency Contact', max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='emergency_phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
