# Generated by Django 5.2.1 on 2025-06-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_teacher_email_teacher_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
    ]
