# Generated by Django 5.2.1 on 2025-05-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20250528_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
    ]
