# Generated by Django 5.2.1 on 2025-06-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_child_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional contact phone number', max_length=20, null=True),
        ),
    ]
