# Generated by Django 5.2.1 on 2025-06-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_teacher_email_remove_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='child',
            name='emergency_phone',
            field=models.CharField(max_length=30),
        ),
    ]
