# Generated by Django 5.2.1 on 2025-06-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_center_phone_alter_child_emergency_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
