# Generated by Django 5.2.1 on 2025-06-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_teacher_email_teacher_phone'),
        ('attendance', '0007_teacher_email_teacher_phone'),
    ]

    operations = [
    ]
