# Generated by Django 5.2.1 on 2025-06-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_late_fields'),
        ('attendance', '0018_attendance_late_attendance_late_reason_and_more'),
    ]

    operations = [
    ]
