# Generated by Django 5.2.1 on 2025-06-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_merge_20250604_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
